### ISSUE TITLE
Export AssemblyScript SDK as part of `massa-web3` tooling

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-web3#10]
Right now including the `as` compiler part of the sdk is problematic. For instance running `npm start` on https://github.com/massalabs/create-react-app-massa returns the following error:
```
Uncaught ReferenceError: require is not defined
    at Object../node_modules/assemblyscript/cli/util/options.js (options.js:250:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/assemblyscript/cli/asc.js (asc.js:38:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at Object../node_modules/massa-web3/dist/web3/SmartContractsClient.js (SmartContractsClient.ts:1:1)
    at Object.options.factory (react refresh:6:1)
```

**Comment by yvan-sraka** [comment]
[AssemblyScript SDK](https://github.com/AssemblyScript/assemblyscript/tree/v0.19.23/lib/sdk) (to compile AS [in browser](https://github.com/AssemblyScript/examples/blob/main/sdk/index.html)) as @BatiGencho painfully, and I painfully experience it, strongly advise not to use a bundler (like `browserify`, `webpack` or `parcel`) but rather to load module in browser using [require.js](https://requirejs.org/) (which something we can btw bundle to save user a `<script />` HTML header).

Be aware, you can also import and use AssemblyScript Compiler in Node.js using [`asc` frontend](https://github.com/AssemblyScript/assemblyscript/tree/main/cli), and that's something slightly different from using it in the Browser!

**Comment by BatiGencho** [comment]
@yvan-sraka There are issues the moment you require or import AS into the sdk and later try to use it under React. I had not only the above shown problem, but various other ones. Do we even need to export AS SDK from massa-web3? If so, what do we benefit from that ?

**Comment by yvan-sraka** [comment]
@damip decide this morning we rather won't resolve this issue for now!
