### ISSUE TITLE
Can't use callSmartContract function

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/massa-web3#15]
When I try to call it this way on my react app : 
```typescript
const baseAccount = {
  privateKey: "2ZyEmw2N9zeUSCxdYeMse2oi4gd9RAECgVbtCJ2GuEozwhQk5L",
  publicKey: "5tuXKh377eV5DNp8xzLo5dhJJVZoAmRuP9CGnKAhGp3xFrhuMv",
  address: "xh1fXpp7VuciaCwejMF7ufF19SWv7dFPJ7U6HiTQaeNEFBiV3"
} as IAccount;

async function feed() {
	await web3Client.smartContracts().callSmartContract({
    fee: 0,
    maxGas: 10000,
    gasPrice: 0,
    parallelCoins: 0,
    sequentialCoins: 0,
    targetAddress: "2Eea7W38sS52psD83W4uEenDketV6cSHWeHHo6P8BtwfmMSxTN",
    functionName: "feed",
    parameter: ""
  }, baseAccount);
```

I get the following error : 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at Hash.CipherBase (index.js:7:1)
    at new Hash (browser.js:9:1)
    at createHash (browser.js:29:1)
    at sha256x2 (index.js:8:1)
    at decodeRaw (base.js:20:1)
    at Object.decode (base.js:40:1)
    at base58checkDecode (Xbqcrypto.ts:14:1)
    at SmartContractsClient.compactBytesForOperation (BaseClient.ts:152:1)
    at SmartContractsClient.<anonymous> (SmartContractsClient.ts:103:1)
    at Generator.next (<anonymous>)
```

I have found this issue that seems related : https://github.com/crypto-browserify/cipher-base/issues/11

**Comment by qdrn** [comment]
Several things were merged during the "rush". Is this still relevant ? If that is the case we should try to fix it before the hackathon if it is not too much trouble.

**Comment by AurelienFT** [comment]
It's not relevant anymore. It has been fixed.
